# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_ID', models.CharField(default='', max_length=255, verbose_name='card_id')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='first_mane')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='last_name')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='phone')),
                ('email', models.CharField(default='', max_length=255, verbose_name='email')),
                ('balance', models.IntegerField(default=0, verbose_name='balance')),
                ('online_cashing_bit', models.BooleanField(db_index=True, default=False, verbose_name='online_cashing_bit')),
                ('max_per_day', models.IntegerField(default=0, verbose_name='max_per_day')),
                ('max_payment', models.IntegerField(default=0, verbose_name='max_payment')),
                ('low_balance', models.IntegerField(default=0, verbose_name='low_balance')),
                ('max_cashing', models.IntegerField(default=0, verbose_name='max_cashing')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(default=0, verbose_name='sum')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
                ('child_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BinBank.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(default=0, verbose_name='sum')),
                ('type', models.IntegerField(default=0, verbose_name='type')),
                ('child_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BinBank.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_ID', models.CharField(default='', max_length=255, verbose_name='card_id')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='first_mane')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='last_name')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='phone')),
                ('email', models.CharField(default='', max_length=255, verbose_name='email')),
                ('balance', models.IntegerField(default=0, verbose_name='card_id')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(default='', max_length=255, verbose_name='place_name')),
                ('longitude', models.FloatField(default=0, verbose_name='longtide')),
                ('latitude', models.FloatField(default=0, verbose_name='latitide')),
                ('enable_bit', models.BooleanField(default=True, verbose_name='enable_bit')),
                ('child_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BinBank.Child')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='parent_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BinBank.Parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='parerent_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BinBank.Parent'),
        ),
    ]
