# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BinBank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='password'),
        ),
    ]
