# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BinBank', '0003_expensetype_incometype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='parerent_ID',
            new_name='parent_ID',
        ),
        migrations.RemoveField(
            model_name='child',
            name='card_ID',
        ),
    ]
