# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BinBank', '0004_auto_20170408_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='parent_ID',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='child_ID',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='child_ID',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='parent_ID',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='child_ID',
            new_name='child',
        ),
    ]
